### ISSUE TITLE
'Yandex.Translator' is a namespace but is used like a variable

### ISSUE THREAD

**Issue by dvdobrovolskiy** [prokhor-ozornin/Yandex.NET.Translator#4]
IYandexTranslator translator = Yandex.Translator(api => api.ApiKey(ConfigurationManager.AppSettings["ApiKey"]).Format(ApiDataFormat.Json));

gives 'Yandex.Translator' is a namespace but is used like a variable
What I am doing wrong?

**Comment by prokhor-ozornin** [comment]
Forgot to add "using Yandex.Translator" namespace perhaps?

See some more usuage examples in IYandexTranslatorExtensionsTests.cs file (Yandex.Translator.Tests subproject).

**Comment by dvdobrovolskiy** [comment]
Nope. It is very strange

Yandex.Translator is a namespace

[ConsoleApp1.zip](https://github.com/prokhor-ozornin/Yandex.NET.Translator/files/3040117/ConsoleApp1.zip)


have same in IYandexTranslatorExtensionsTests

**Comment by prokhor-ozornin** [comment]
Add using Yandex.Translator inside your app's namespace.
This example compiles ok for me:

```
using System;

namespace ConsoleApp1
{
  using Yandex.Translator;

  class Program
    {
        static void Main(string[] args)
        {
            var translator = Yandex.Translator(api => api.ApiKey("test"));

            Console.WriteLine("Hello World!");
        }
    }
}
```

**Comment by dvdobrovolskiy** [comment]
Way better now. Cool. Thanks
